package com.hjy.microfirst.domain.mapper;

import com.hjy.microfirst.domain.Book;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_book
     *
     * @mbg.generated Sun Apr 26 18:01:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_book
     *
     * @mbg.generated Sun Apr 26 18:01:50 CST 2020
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_book
     *
     * @mbg.generated Sun Apr 26 18:01:50 CST 2020
     */
    Book selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_book
     *
     * @mbg.generated Sun Apr 26 18:01:50 CST 2020
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_book
     *
     * @mbg.generated Sun Apr 26 18:01:50 CST 2020
     */
    int updateByPrimaryKey(Book record);
}